server:
  port: 8088
file:
  path: C:\upload\
access:
  path: C:\upload\

spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

