server:
  port: 8088
file:
  path: D:\upload\
access:
  path: D:\upload\

spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  datasource:
    url: jdbc:mysql://localhost:3306/数据库名称?serverTimezone=GMT%2B8&useSSL=true
    password: root
    username: root
    driver-class-name: