server:
  port: 8088
file:
  path: C:\upload\
access:
  path: C:\upload\

spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  datasource:
    url: jdbc:mysql://localhost:3306/db_rules_application?serverTimezone=GMT%2B8&useSSL=true
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver